version: "2"

services:
#  app:
#    build:
#      context: .
#      dockerfile: ./docker/app/Dockerfile
#    ports:
#      - 8080:8080
  db:
    image: mysql:5.7
    container_name: ktor_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/conf:/etc/mysql/conf.d
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306